# Generated by Django 3.0.7 on 2020-06-09 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200609_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='images',
            field=models.ManyToManyField(blank=True, to='api.Image'),
        ),
    ]
